services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    image: harris-salimo/expense-tracker:latest
    ports:
      - "9000:9000"
    env_file: .env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    restart: always

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html/public:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./storage/logs:/var/www/html/storage/logs
    depends_on:
      - app
    restart: always
