name: tests

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10.6.2
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install Node Dependencies
        run: pnpm install --frozen-lockfile

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Build Assets
        run: pnpm build

      - name: Cache files
        run: php artisan optimize:clear && php artisan config:cache && php artisan route:cache && php artisan view:cache

      - name: Tests
        run: ./vendor/bin/pest
